title: Confessions of a master procrastinator
baseurl: /blog
email: mourjo@mourjo.me
markdown: kramdown

# Tracker
analytics: UA-115015256-1


#optimization -- compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []


sass:
 style: compressed

exclude:
- README.md


plugins: [jekyll-seo-tag, jekyll-paginate]
