title: Mourjo Sen's Blog
description: Thoughts of a software engineer about life, tech and everything in between. A place to put down my thoughts for my own recollection more than anything else. If you like it, be sure to drop me an email!
baseurl: /blog
url: https://mourjo.me
author:
  twitter: mourjo_sen
email: mourjo@mourjo.me
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title/

twitter:
  username: mourjo_sen
  card: summary

social:
  name: Mourjo Sen
  links:
    - https://github.com/mourjo
    - https://www.linkedin.com/in/mourjo
    - https://www.facebook.com/sen.mourjo
    - https://twitter.com/mourjo_sen

# Tracker
analytics: UA-115015256-1

sass:
    style: compressed

exclude:
- README.md
- Makefile
- Gemfile

plugins:
  - jekyll-seo-tag
  - jekyll-feed

feed:
  tags:
    except:
      - hidden
