#!/bin/sh
echo "RUNNING PERMALINK MIGRATION `pwd`";
for category in `ls _site | grep tech`; do
  for year in `ls _site/$category`; do
    for month in `ls _site/$category/$year`; do
      for day in `ls _site/$category/$year/$month`; do
         for postdir in `ls _site/$category/$year/$month/$day/`; do
           if [[ $postdir != *"html" ]];then
             echo "Migrating $postdir"
             cp "_site/$category/$year/$month/$day/$postdir/index.html" "_site/$category/$year/$month/$day/$postdir.html";
             git add "_site/$category/$year/$month/$day/$postdir.html";
           fi;
         done;
      done;
    done;
  done;
done;
