name: Latest Medium blog post workflow
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@1.2.5
        with:
          max_post_count: 10
          feed_list: "https://medium.com/feed/@mourjo_sen"
          readme_path: "_posts/2020-09-03-medium-index.md"
          template: "- [$title]($url)<span class='copy'>&nbsp;—&nbsp;$date</span>$newline"
          date_format: "dd mmm yyyy"
          tag_post_pre_newline: true
